---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-secret
  namespace: argocd
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    admin.password: AgCJDZ2qheMqIs1nO8bXPWcMPvuj/jEheRbVL79oY1spYgVU9T0h4LDA6qHBERQAOw097qv1oZmJanUOUfGQV/smf0SeUyC18X93rlmSfSivcwmw3AiI8jgqSgreeYQjHC0pN58uV+KIo0/nfaXgAz5VzYURxmFYlYB7AqXpafK+s3protdugEhhhNyzaSEMxgXrunAzqvO3su/ZKC3oa2GxWkZbgCdxwzPKsKGMrFM8cm5KROSYmurPua2nQfuIAnmvCZzX94tya1/JMQUFQpxhLDxeKdpAtG8GWgpbXKLYbcnYlWmkJhr5QO6eirkglpAKqyHTuBLijtcYReDmP3Bn2ppiWegaDFZiz66eQ+loXe90s7iWw1O6pDr9fuSZkiAW6k57Lm6VGd30UJWEHN4qoveiykpRowXNs2W+aUQBG1bmwfGQQmEaHo8Ak72xFTtLqeicNIoaPAeq8o/vLG6h8yLMH972RUhyBs45eoVOgPT+gZTFMExSYf1pwZ3x2av1IrAmlCesBA7EzbsA0UNXV5RqkMoT7R0U1/aCkgREYE9v12xRTd8zEVwLpwc6tUHNRTA3oeqBkFr0I/mb6meSymXqDBD84FdMawGXvwsFJZxOi8bMGdQAfW0DXRmQ2x1CjOyLlCKrHUbPnFB5JANjqxDLmjrD7MOh1+eW4ROPG4YoKhAMcx1MJS0aXw0noWU0n5OEZMfGOSAL8QBRCpOv/Y/hQh6coqiXLaC5VeGPcZ8MoOBXGAK+5Nc9+yorXipx1dcVkFZ5VEIB6no=
    admin.passwordMtime: AgBiEFSEzssJ0Dqvon9KvgXEKNoxedb74V+HxqRfUAvWceaSrCHtmk14/tOKXYND7+6Ams4FPpiCQk3KIgIDnHKNMdocZ91QiPpf7jKeX8OTc7Pw3u5WcoCUb+2fJTEc+EJQcLyItOb7ZcoCgNgAURQOB5/r2XpzxlxdbAr1l5M0WLDWugqvPlZNMq8zs01t2BRI1Y5ci8HcdqnRgLfZnyhzlqnKHr9KjoBE6lwet+EpKHk6gIRyjgbq93FLREhO4q1QWkrya8NRyO1e8A3ZbToLScGsPSQJzuD75DafAHDrh84ZkRomeOaP78aYQSd0GlTFahOtwS7n/+3l5sPN3wnU1JifCioQIc4yuDK9j1XuI/YZxo6PBycvpUgL8Erzjx4CHCpq+/kEhmzeuKgdxKaHTcjP696Rf2pt82N/LfY4+jryP0MW9n4HV87IGjjUFWj8syak9BUq2CYbPTJjmP/Yre7E27++pbKNngyGmxMrE5dOgpzLLlT7xfBfAp7ptDQbnRXo/eLEqfCrLbxi0NsrqxnMjQKce2ISyTuyrKFanvbZrkDvoxWLS6dFO1CLOfEeOSBa+sygIsarnCIaC/zv+FFuOKCAojmGX2X1IS2yhYXPE5jmM/DZwQiivT46M2XAkobPXUSCFUSXP62HvAkFcYlF1xhZYqBdSLyDgWWSzyhSrtuXD+N6SktsOUsazXj8m0oYcvHBRC/7fwL34/yT4fdf0w==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd
    type: Opaque
