---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgBkcEhHoWrxC/tY+/8tXlrwSx3iWbbNlyG32gFYgy2h+nw1/X1l6KydSTmBjGXQ9AOOVqdAC+sPpUUYA5yLAfT8Q9Kk0LUpmwB7JzkIQtdI2uS1B0LOyhz/iPOPVXK+9LmlS+lqOg8tr9HsE1NsTSykYE3d4zU1U0PDQF8ysH+6EJocL1XVCG/5eQGSHNaIpaCWfQ7JOW0pPK6rPY662wrWC7YhF6o3BLeaiHsYEdrnAlkHGyonT+SpWNcZWkux0awyq6Ho07ODRmQoTyrSswU5wD3NW1a1Uc/gx1iB0KQIUO/9fcbsOfLo6qq4J+nOopwqTa9Nqi5l3HPHQeP4DyZXRQRnFWH/5bulQBWercYQEzA/WTdH2g37IkJDfHwF5E1GmpHtlj1dXWz3hMdfaP7WHucmrYSIBlq3A+4UalxRs3ufyA+qDw6BzQSGCSZ0G3H32Ncg0paECluiSflIj1hJ0a0jLgCaMO3zsyScwWXiSKqmoGl9CTT5ML0NbtZ9vu/JSvwpxuOSJM8fEhOKaDw+5oZ5QFDk2lYpC1zMo52PwvEuJkKLep7Y0g9qSPNeexL+la5qmt/GH0q2jgTLJLoxnNPGT2dB9hOfBUXjaSX0hGOBYf6sU+MVBkB5U45uw5kxKrNxHXn/nLq2hKmF3lME1asv40ijxzpMyb7gcD83bb1EtYxN4YAVvKdo2orktIeI58gechR0Jjsk119tOT37E+V1+0SsS4aWO+3RXfR9oXFk5sCWxiwwUL9f0MpGnPxdsVG4oz4em4H+h7Ourz5MkmLN5/heiY8WprXntmx3mo6ckSSFDLyo5ONrfZmLOQEY+JVlqdDNLkVCNCH2Tme0odiCZV+1CCGKp8bzvwBotw18Jyd4MEhA26I9bboDTshrPq1/WRm50Z//NArlGw07UzDY4dvwdt8QwleXeSCP
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-credentials
      namespace: cloudflared
