---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCZTWmCkR2xcSfmiE3JN6o00T1jUnZ+spG103ka4cwbR71Qewmr4g8Wz01+DWDmeQtJjvEOht84UvytBGS6S23jJN4Krpidhc4wz4KjC4FJVJKT0fuZwPlH/v5d4S0Jh6tIHuykl1+9hVEPKcEmX85HYVAO6P34F+aW4s2da9xxY8e5kCHpLbIrRFdtCpYhIEmu8gfW5WEexcw17Pz73oe++G7yVCDnOTD7hLtM/hvALzah3wsrC/lSKBVagWfiL49nCTqid1bn0bVvPNcaZtNE9A07FTI6xbLVRAP5DA+BxuKCj5hF8l2X4+1efHQYo+QyuAjgqLM3Kte4QLwX3lrykQznw3NsPZ32c1XJhhaB6ovxUjBT2czKcybsC+DUIxQ7VORS599IM0RV9b1XmmeCwqoQs/RgCx8Zvv8+QsRTHzYe85UeUh3mmBolltWhE3HAIUrcVxg97KU9fBMbKp6H6FW1/VJwzPgLT1N1b417CNdn4jNNgtyltXR8HBWHDSxywIcqNBJyRhY4RddeFGE/UtL3UoGhuOfIF+vmMxP3Zd2Lvn72X5zBrMUTbs3lhZz088kxrYxGP0BQc/5kGQ3FHjXuHV/86hR10dllqi4yhBU1BK4NxRNADDITxHlYyYpqxztON5qSfF8IH22jdoQewwff6KUTonJZkDgYktGtEsoTnbHwMxW7cQ2gdYLEm9GfYuxORp+dbQ==
    admin-user: AgBYvNkI2hux4Z5NOYZv4lSX7QZh+v/QL6KAvlkvWzpVaVFH+Sadkam63IG3hbJ24RauyUD1PqXR56qoHeRzwqCakswgibUV8Dk6y4LWXF8hWOluPxUYUtD5zytog3+hIS1j7ZyMRBbI0TbhRhhEmbm6VkAwGSZISTPjDMLz9fBu1rBgZK5WqK3DBXlE10nK9kEAXbD5EZn453jpyHsrzXMoIJbrBBfaN5bDSwn/da2Lje9MMAuwMBOQB6cYOgE1vI03WUslwWD0tSvyqHnyPquPks5YBnmf6W3j5dihJNrs9yYg5NY9HgeADQuwYGVvNoRLh9t1e/iPxktd0FTD5vTht9jG905Hq0YrnM7TgwjHPiKBZb7mUTNMcXLoerqQziIterTH30O5XcYsY/ReeyGalUGSe4WBkXiOV4OBiLP0J9VUsKqenBWQvuvi/LQe18qOnEqEFDt8FUzvc2Gp06+GKpe3TwFZJ7ZJDrDNJLtFbQNaU/TiPBFoAe+zFqf0WqkPSEt4gl3xVKIZI55mr0zDu533fPL4eStZNYRLWAgzLhA6jtC3Cqm60EWlbw3Ifcjxb8YGLSIUs8UN6wlAwS8offKEq8QIMPsnnuBgS7O6XpfYQUZyDex+hMrgsak7MHogI68b0FSWAE0pVvajC6zyF/JV0f6QiuBfko3mZuMzYc+S0lR/5YEmxCiZ5FdK4GhA++vG0g==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
    type: Opaque
